version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10-alpine
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ishmatov/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: ishmatov/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: ishmatov/taski_gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80