version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    image: ishmatov/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static

  frontend:
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    image: ishmatov/taski_frontend
    volumes:
      - static:/frontend_static

  gateway:
    build: ./gateway/
    image: ishmatov/taski_gateway
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80